version: '3.5'

services:
  gunicorn:
    build: 後端/
    volumes:
      - ./好的/:/opt/好的/:ro
    networks:
      - default
      - nginx-bridge
    environment:
      VIRTUAL_HOST: "dbkaxabu.ithuan.tw"
      LETSENCRYPT_HOST: "dbkaxabu.ithuan.tw"
      LETSENCRYPT_EMAIL: "ithuan+dns@ithuan.tw"
    restart: always

networks:
  nginx-bridge:
    external: true

